### ISSUE TITLE
A lot of bugs!

### ISSUE THREAD

**Issue by OstenTV** [MrCrayfish/MrCrayfishDeviceMod#57]
In the new 0.2.0 release, I have found a lot of bugs

1. The server crashed a few times.
2. You can't sit in chairs.
3. Endermail notifications have a small rendering bug
4. Chairs leave a ghost block when broken.
5. Chairs seem to crash the server.
6. Routers and printers don't show their name in the inv.

Here is a video showing the notification rendering bug
http://ftpp.ostentv.dk:8011/GitHub/Device-mod/%2357/Desktop%2001.12.2018%20-%2005.24.55.06.mp4

Here are the crash reports
http://ftpp.ostentv.dk:8011/GitHub/Device-mod/%2357/crash-2018-01-12_05.18.28-server.txt
http://ftpp.ostentv.dk:8011/GitHub/Device-mod/%2357/crash-2018-01-12_05.19.40-server.txt
http://ftpp.ostentv.dk:8011/GitHub/Device-mod/%2357/crash-2018-01-12_05.30.20-server.txt
http://ftpp.ostentv.dk:8011/GitHub/Device-mod/%2357/crash-2018-01-12_05.33.28-server.txt
http://ftpp.ostentv.dk:8011/GitHub/Device-mod/%2357/crash-2018-01-12_05.53.19-server.txt
http://ftpp.ostentv.dk:8011/GitHub/Device-mod/%2357/crash-2018-01-12_05.58.57-server.txt

**Comment by MrCrayfish** [comment]
Should all be fixed in
https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/e37a4561fad0072a20db7d900dac66df2931a5ff
https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/9aa84dd9c1491f20e425971aed2d093e377aa906
https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/a7f9f7c87ab70bb18b986cdcd528d717e1e94b91

**Comment by OstenTV** [comment]
Did you also fix the other bugs I added to this post afterwards?

**Comment by MrCrayfish** [comment]
Yes. Check the commits

**Comment by OstenTV** [comment]
Printers and routers still don't show their name in the inventory.

**Comment by MrCrayfish** [comment]
Oh I see the issue, it's on server. Will fix :)
